version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: '1234'
        POSTGRES_DB: empartydb
    ports: 
        - "5432:5432"

  app:
    image: emparty/pugsod:backend
    ports:
        - "8080:8080" 
    depends_on: 
        - db
    networks: 
        - default