name: Deploy App to AWS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIATWA57VH5L4IVAOSX
          aws-secret-access-key: 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
          aws-region: ap-southeast-2

      - name: generate ssh key
        run: cat > ~/.ssh/known_hosts
      
      - name: copy file to aws
        run: |
          scp -i "emparty.pem" ./docker-compose.yml ec2-user@ec2-13-54-221-181.ap-southeast-2.compute.amazonaws.com:/home/ec2-user
      
      - name: run docker on aws
        run: |
          ssh -tt -i "emparty.pem" ec2-user@ec2-13-54-221-181.ap-southeast-2.compute.amazonaws.com
          docker-compose down
          docker-compose pull
          docker-compose up