name: Deploy App to AWS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Edit permission
        run: |
        chmod 400 emparty.pem
        cat ~/.ssh/known_hosts
      
      - name: Deploy Docker-Compose to AWS EC2
        run: |
          ssh -tt -i "emparty.pem" ec2-user@ec2-13-54-221-181.ap-southeast-2.compute.amazonaws.com
          docker-compose down
          docker-compose pull
          docker-compose up -d