name: Deploy App to AWS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Edit permission
        run: chmod 400 emparty.pem

      - name: Deploy Docker-Compose to AWS EC2
        run: |
          ssh -i "emparty.pem" ec2-user@ip-172-31-7-249
          cd ~/ec2-user/emparty
          docker-compose down
          docker-compose pull
          docker-compose up -d