name: Deploy App to AWS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentilas@v1
        with:
          aws-access-key-id: AKIATWA57VH5L4IVAOSX
          aws-secret-access-key: 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
          aws-region: ap-southeast-2
