name: Go Build and Publish Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      working-directory: ./backend
      run: docker build -t emparty/pugsod:backend .

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      working-directory: ./backend
      with:
        name: emparty/pugsod
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
