name: Go Build and Publish Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v2

    - name: Build Backend Docker Image
      run: docker build -t emparty/pugsod:backend .

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        file: ./Dockerfile
        push: true
        tags: emparty/pugsod:backend

