name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependency and run server
      run: |
        cd ./backend
        go mod vendor
        go run server

    - name: Test
      run: |
        cd backend/tests/shoptest
        go test